CREATE FUNCTION _fcGetAuth(
	@KEY	VARCHAR(255)
) RETURNS INT
AS
BEGIN
	DECLARE @ACCOUNTNO INT;
	SELECT @ACCOUNTNO = ACCOUNTNO
	FROM
		dbo.[Sessions]
	WHERE
		expires >= getdate()
		AND [sid] = @KEY;
	RETURN @ACCOUNTNO;
END
